#!/usr/bin/env python3
"""
build_school_ratings.py
=======================
Builds data/school_ratings.js for the buy_house_ca (CA School Rating Map) site.

Reads the REAL data files from the sibling ca_school_finder repo:
  - schools.js         window.SCHOOLS        (CA DOE directory: name, level, lat, lon)
  - ratings.js         window.SCHOOL_RATINGS (CAASPP 1-10 decile by year)
  - accountability.js  window.SCHOOL_ACCT    (CA Dashboard, incl. 2025 ratingYear)

Output: window.SCHOOL_POINTS = [ {n, lv, city, d, lat, lon, r:{2025,2026,2027,2028}} ]
  lv: "E" | "M" | "H"
  r : integer-ish rating (1 decimal) per year. 2025 = real; 2026-2028 = linear extrapolation.
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC  = os.path.abspath(os.path.join(HERE, "..", "..", "ca_school_finder", "data"))
OUT  = os.path.abspath(os.path.join(HERE, "..", "data", "school_ratings.js"))

LEVEL_CODE = {"Elementary": "E", "Middle": "M", "High": "H"}


def load_js_global(path):
    """Read a `window.X = <json>;` file and return the parsed JSON object."""
    with open(path, "r") as f:
        txt = f.read()
    # Find the start of the JSON payload (first '{' or '[' of the assignment),
    # skipping comment headers that may themselves contain '=' characters.
    m = re.search(r"window\.\w+\s*=\s*", txt)
    start = m.end() if m else 0
    body = txt[start:].strip()
    if body.endswith(";"):
        body = body[:-1].strip()
    return json.loads(body)


def clamp(v, lo=1.0, hi=10.0):
    return max(lo, min(hi, v))


def linfit(points):
    """points: list of (x, y). Return slope (least squares). 0 if <2 points."""
    n = len(points)
    if n < 2:
        return 0.0
    mx = sum(p[0] for p in points) / n
    my = sum(p[1] for p in points) / n
    num = sum((p[0] - mx) * (p[1] - my) for p in points)
    den = sum((p[0] - mx) ** 2 for p in points)
    return num / den if den else 0.0


def main():
    schools = load_js_global(os.path.join(SRC, "schools.js"))
    ratings = load_js_global(os.path.join(SRC, "ratings.js"))
    acct    = load_js_global(os.path.join(SRC, "accountability.js"))

    out = []
    kept = skipped = 0
    for s in schools:
        sid = s.get("id")
        lat, lon = s.get("lat"), s.get("lon")
        lv = LEVEL_CODE.get(s.get("level"))
        if lat is None or lon is None or lv is None:
            skipped += 1
            continue

        # Gather historical (year, decile) rating points.
        pts = []
        R = ratings.get(sid)
        if R and isinstance(R.get("r"), dict):
            for y, val in R["r"].items():
                try:
                    pts.append((int(y), float(val)))
                except (TypeError, ValueError):
                    continue

        # Real 2025 rating from CA Dashboard accountability data.
        A = acct.get(sid)
        real2025 = None
        if A and A.get("ratingYear") is not None:
            real2025 = float(A["ratingYear"])
            yr = int(A.get("year", 2025))
            pts = [p for p in pts if p[0] != yr]
            pts.append((yr, real2025))

        if not pts:
            skipped += 1
            continue

        pts.sort()
        slope = linfit(pts)

        # Anchor: prefer the real 2025 point; else the most recent available.
        if real2025 is not None:
            anchor_y, anchor_v = 2025, real2025
        else:
            anchor_y, anchor_v = pts[-1]

        def val_for(year):
            return round(clamp(anchor_v + slope * (year - anchor_y)), 1)

        r = {
            "2025": val_for(2025),
            "2026": val_for(2026),
            "2027": val_for(2027),
            "2028": val_for(2028),
        }

        out.append({
            "n":   s.get("name", ""),
            "lv":  lv,
            "city": s.get("city", ""),
            "d":   s.get("district", ""),
            "lat": round(float(lat), 5),
            "lon": round(float(lon), 5),
            "r":   r,
        })
        kept += 1

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("/* AUTO-GENERATED by scripts/build_school_ratings.py\n")
        f.write("   Source: CA DOE directory + CAASPP deciles + CA Dashboard (2025).\n")
        f.write("   lv: E/M/H.  r: 1-10 rating per year; 2025=real, 2026-2028=linear extrapolation. */\n")
        f.write("window.SCHOOL_POINTS = ")
        json.dump(out, f, separators=(",", ":"))
        f.write(";\n")

    print(f"Wrote {OUT}")
    print(f"  schools kept: {kept}, skipped (no coord/level/rating): {skipped}")


if __name__ == "__main__":
    main()
